_wandb:
    value:
        cli_version: 0.26.1
        e:
            wdb5xl8bpbbg6wcskv8pm7ptw92eu9hr:
                args:
                    - --layer
                    - "10"
                codePath: src/sae/train/train_sae.py
                codePathLocal: src/sae/train/train_sae.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "942055424"
                email: abuqutishkhaled@gmail.com
                executable: /workspace/Dataset-Curation/.venv/bin/python3
                git:
                    commit: 8599b7d1e743132c1ed604e2d4a6dc282066f810
                    remote: https://github.com/kindaMashal/Dataset-Curation.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Server Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Server Edition
                      uuid: GPU-97920117-6912-ffa4-4cf8-95ac06abdda8
                host: 137002d06bf5
                memory:
                    total: "1622817189888"
                os: Linux-6.8.0-111-generic-x86_64-with-glibc2.39
                program: /workspace/Dataset-Curation/./src/sae/train/train_sae.py
                python: CPython 3.11.13
                root: /workspace/Dataset-Curation
                startedAt: "2026-05-12T13:12:44.254260Z"
                writerId: wdb5xl8bpbbg6wcskv8pm7ptw92eu9hr
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
            "3":
                - 13
            "4": 3.11.13
            "5": 0.26.1
            "6": 5.8.0
            "12": 0.26.1
            "13": linux-x86_64
